repos:
  # Black format checker
  - repo: https://github.com/psf/black
    rev: 25.9.0 # Use the same version as in requirements-dev.txt
    hooks:
      - id: black
        name: black-format-checker
        description: "Check Python code formatting using Black"

  # isort import sorter
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0 # Use the same version as in requirements-dev.txt
    hooks:
      - id: isort
        name: isort-import-sorter
        description: "Sort Python imports using isort"
        args: ["--profile", "black", "--line-length", "120"]

  # Flake8 linter
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0 # Use the same version as in requirements-dev.txt
    hooks:
      - id: flake8
        args: [
          "--max-line-length=120", # To be consistent with chosen line length
          "--extend-ignore=E203,W503" # To be consistent with Black formatting
        ]
        name: flake8-linter
        description: "Lint Python code with Flake8"

  # Custom hook to run tests with coverage
  - repo: local
    hooks:
      - id: tests-with-coverage
        name: Run tests with coverage
        description: "Run the test suite and measure code coverage"
        entry: bash -c coverage run -m unittest discover -s tests -p "*_test.py"
        language: system
        types: [python]
        always_run: true
        stages: [pre-commit]