services:
  db:
    image: postgres:16
    container_name: postgress_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db/schemas:/docker-entrypoint-initdb.d/
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always

volumes:
  db_data: