[tool.black]
line-length = 120
target-version = ['py312']
skip-string-normalization = true

# directories to exclude from formatting
exclude = '''
/(
    \.venv
    |\.git
    |__pycache__
)/
'''

[tool.isort]
profile = "black"
line_length = 120
known_third_party = [
    'numpy',
    'pandas',
    'sqlalchemy',
    'requests',
    'streamlit',
]
skip = [
    ".venv",
    ".git",
    "__pycache__"
]