[tool.black]
line-length = 120
target-version = ['py310', 'py311', 'py312']
include = '\.pyi?$'  # include Python files

# directories to exclude from formatting
exclude = '''
/(
    \.venv
    |\.git
    |__pycache__
    |db_data
    |\.env
    |venv
    |logs
)/
'''

[tool.isort]
profile = "black"
line_length = 120
known_third_party = [
    'numpy',
    'pandas',
    'sqlalchemy',
    'requests',
    'streamlit',
]
skip = [
    ".venv",
    ".git",
    "__pycache__",
    "db_data",
    ".env",
    "venv",
    "logs",
]

[tool.coverage.run]
branch = true
source = ["tests"]